### ISSUE TITLE
Minecraft Refuses to Load with latest version on Prism Launcher

### ISSUE THREAD

**Issue by G93d14** [HydraheadHunter/Data-Driven-Stacks#10]
A copy of my log: https://mclo.gs/2xJjJsT

I will revert to the previous version for now.

**Comment by G93d14** [comment]
log with previous version in case it is useful: https://mclo.gs/BzOcd7l

**Comment by HydraheadHunter** [comment]
Before I look into this, if you'd be willing to check if [v0.9.3](https://modrinth.com/mod/data-driven-stack-sizes/version/0.9.3-1.21) also crashes your game, I'd greatly appreciate it. 

I changed quite a few things on the back-end for this version to get player/non-player stack size differences working acceptably well, and it'd be good to know if the new, most-recent, version is still causing you problems or if by some miracle I fixed it accidently.

**Comment by G93d14** [comment]
I wasn't able to check v 0.9.3, but 0.9.4 still crashes my game.
[v0.9.4 log](https://mclo.gs/e6zHLQU)

**Comment by HydraheadHunter** [comment]
(0.9.3 had a major crashing bug unrelated to this issue which I caught immediately after uploading but not before this comment, and I forget to get around to correcting my most recent version).

Yep, certainly does. Something changed in the fabric load twixt FabricLoader 15.11 and FabricLoder 16 that broke at one of my mixins. I'll see what I can do about fixing the problem for ya.

**Comment by HydraheadHunter** [comment]
I've updated to Fabric Loader 16.0 is a branch, and it seems to really just not not liking `ScreenHandler;modifyItemStack2(...)`

I don't understand why it doesn't like the method, but as a hot-fix, I've built a compatability version which removes the offending method without replacement. The removed method is responsible for changing 'click-and-drag' behavior of items configured to have different stacksizes twixt player/non-player inventories, so this compatability version won't have that feature.

But, the game shouldn't crash.

Please, check [Data Driven Stack Sizes 0.9.4-1.21-FL16-compat](https://modrinth.com/mod/data-driven-stack-sizes/version/R2LjhIa1) to see whether this is the case.

**Comment by G93d14** [comment]
I've been using fabric loader 16 since I started playing in 1.21, and 0.9.0 was working fine there. I'm not using differing stack sizes for players anyway, so if that's the only change I don't think it will affect my game. 

I'll check it out when I next open minecraft.

**Comment by G93d14** [comment]
it loads up with this compatibility version fine. Here is the [log](https://mclo.gs/eYcmrup) for your reference.

**Comment by G93d14** [comment]
wait no it's not actually working, nothing new stacks above 64

**Comment by HydraheadHunter** [comment]
Please check if the problem persists in [v0.9.5](https://modrinth.com/mod/data-driven-stack-sizes/version/89OJ7x6e).

Please also check that if you were using the `villager_stack_less` tag that you've renamed the directory from `entity` to `control`.

**Comment by G93d14** [comment]
hey, I haven't been able to check the villagers_stack_less part yet but v0.9.5 works fine qith fabric loader v0.16.

**Comment by HydraheadHunter** [comment]
Wonderful. Then i'll be closing this issue
